### ISSUE TITLE
Webapp context reload causes ClassCastException with sticky sessions

### ISSUE THREAD

**Issue by ghost** [magro/memcached-session-manager#123]
_From [rusla...@gmail.com](https://code.google.com/u/104677000896359185454/) on February 04, 2011 13:37:53_

<b>What steps will reproduce the problem?</b>
1. Some package in jar in WEB-INF/lib&#13;
2. Init app, put object in session&#13;
3. Redeploy&#13;
4. Try to access object in session&#13;
5. ClassCastException&#13;
&#13;
<b>What is the expected output? What do you see instead?</b>
&#13;
Working without ClassCastException&#13;
&#13;
<b>What version of the product are you using? On what operating system?</b>
&#13;
tc7-1.4.0-RC1 &#13;
Tomcat 7.0.6&#13;
JDK 1.6.0_18 x86&#13;
Windows 7 x64&#13;
&#13;
<b>Please provide any additional information below.</b>
&#13;
Object o = session.getAttribute("cache");&#13;
ru.cache.Cache cache = (ru.cache.Cache) o;&#13;
&#13;
java.lang.ClassCastException: ru.cache.CacheImpl cannot be cast to ru.cache.Cache&#13;
    at ru.web.application.WebContext.getCache(WebContext.java:349)&#13;
    at ..&#13;
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)&#13;
&#13;
Both ru.cache.Cache is interface, ru.cache.CacheImpl is class,&#13;
both in same jar, this jar is inside WEB-INF/lib.&#13;
&#13;
Doublechecked not having this class in application server classpath.&#13;
&#13;
When running under debugging, surprisingly&#13;
o.getClass().getClassLoader() != ru.cache.Cache.class.getClassLoader()&#13;

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=80_

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on February 04, 2011 04:51:19_

How do you create and add the "cache"? Is it possible, that it's a cglib proxy, or is it just session.setAttribute("cache", new CacheImpl())? Which serialization strategy are you using (java, kryo, javolution)?

**Status:** Accepted

**Comment by google-code-exporter** [comment]
_From [rusla...@gmail.com](https://code.google.com/u/104677000896359185454/) on February 04, 2011 05:10:17_

i just do session.setAttribute("cache", new CacheImpl()). Default java serialization is used, my manager configuration is following:

<Manager className="de.javakaffee.web.msm.MemcachedBackupSessionManager"
	memcachedNodes="nodename:hostname:11211"
	failoverNodes=""
	requestUriIgnorePattern=".*\.(png|gif|jpg|css|js)$"
	sessionBackupAsync="true"
	sessionBackupTimeout="100"
	copyCollectionsForSerialization="false"
/>

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on February 05, 2011 16:33:58_

I just create a sample webapp with a servlet that can put stuff into such a Cache/CacheImpl (implementing Serializable also) and list the content of the cache, but I cannot reproduce your issue:
<a href="https://github.com/magro/msm-sample-webapp/tree/simpleservlet" rel="nofollow">https://github.com/magro/msm-sample-webapp/tree/simpleservlet</a>&#13;
&#13;
The following should work:&#13;
&#13;
Install deps and build the war:&#13;
$ ./install-mvn-deps.sh&#13;
$ mvn package&#13;
&#13;
Start memcached:&#13;
$ memcached -p 11211 -u memcached -m 64 -M -vv &amp;&#13;
$ memcached -p 11212 -u memcached -m 64 -M -vv &amp;&#13;
&#13;
Start tomcats:&#13;
$ ./runtime/tomcat1/bin/catalina.sh run &amp;&#13;
$ ./runtime/tomcat2/bin/catalina.sh run &amp;&#13;
&#13;
Populate/list the content of the cache which is stored in the session:&#13;
- In your browser request http://localhost:8081/put?foo=bar (or use curl or whatever)&#13;
- To see that the cache in the session is populated: http://localhost:8081/list&#13;
-&gt; The response body should contain "foo=bar"&#13;
&#13;
Load this session/cache in another tomcat to see that the session/cache can be deserialized:&#13;
- Request http://localhost:8082/list&#13;
-&gt; The response body should contain "foo=bar"&#13;
&#13;
Also, when running the tomcat I can redeploy the webapp via&#13;
$ mvn package&#13;
and after the context was restarted I still can list the session/cache content.&#13;
&#13;
What's different in your case? Can you modify this sample app so that I can reproduce your issue?

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on February 07, 2011 02:52:31_

Btw, I just pushed a new version of the sample with also tomcat 6.0.32 and a new msm 1.4.0-RC2 (which only contains fixes for #79 and #81, which should not affect you).

**Comment by google-code-exporter** [comment]
_From [rusla...@gmail.com](https://code.google.com/u/104677000896359185454/) on February 07, 2011 03:47:04_

Sorry I can`t run it, I don`t have POM and my target environment is not Linux. However I`ve made simpler test, just unpack over fresh apache-tomcat-7.0.6. 

I am experiencing odd behaviour - on subsequential request, value is not stored into session. Also in log, I see double initialization of MSM.

**Attachment:** [testmsm-artefacts.zip](http://code.google.com/p/memcached-session-manager/issues/detail?id=80#hc5)
