### ISSUE TITLE
Re-using session ids breaks Spring Security

### ISSUE THREAD

**Issue by ghost** [magro/memcached-session-manager#185]
_From [one...@energyhub.net](https://code.google.com/u/104435162650559232740/) on June 13, 2012 23:05:09_

<b>What steps will reproduce the problem?</b>
1. m-s-m master branch with Spring Security&#13;
2. Re-using the session id after log-in causes a redirect to login page after login. Possibly some kind of race condition caused by SS invalidating the unauthenticated session during login, not sure.&#13;
&#13;
&#13;
<b>What is the expected output? What do you see instead?</b>
&#13;
Creating a new session should lead to a new JSESSIONID. That session should be valid.&#13;
&#13;
<b>What version of the product are you using? On what operating system?</b>
&#13;
Current master (<a href="/p/memcached-session-manager/source/detail?r=f907715023830a853039b8747231b946a450e08c">f907715023830a853039b8747231b946a450e08c</a>) on Ubuntu 10.04, tomcat6.&#13;
&#13;
<b>Please provide any additional information below.</b>
&#13;
The attached patch fixes this issue by never re-using the sessionId.

**Attachment:** [m-s-m.patch](http://code.google.com/p/memcached-session-manager/issues/detail?id=143)

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=143_

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on June 14, 2012 01:06:58_

To use the specified (requested) sessionId is the behaviour of all tomcat session manager implementations (implemented in ManagerBase.createSession(String sessionId)). To change the behaviour for msm I'd check very carefully if this is really needed.

Can you please provide a working sample that I can use to reproduce your issue?
Alternatively provide request/response headers and debug logs of msm for the problematic work flow so that I can see what's happening.

**Comment by google-code-exporter** [comment]
_From [one...@energyhub.net](https://code.google.com/u/104435162650559232740/) on June 14, 2012 11:09:12_

Here's two MSM logs with and without the patch. In each case 

Without patch (re-use session id and getting logged out after login)
<a href="https://gist.github.com/2931870" rel="nofollow">https://gist.github.com/2931870</a>&#13;
&#13;
With patch (ignore old session id, use a new one)&#13;
<a href="https://gist.github.com/2931745" rel="nofollow">https://gist.github.com/2931745</a>&#13;
&#13;
&#13;

**Comment by google-code-exporter** [comment]
_From [one...@energyhub.net](https://code.google.com/u/104435162650559232740/) on June 14, 2012 11:34:26_

Ah. I have disabled the Spring Security 'session fixation strategy' and it now works without the patch. SS must have been invalidating the authenticated session because the session id was unchanged. As such this is not a bug in m-s-m.

Perhaps there's a way to specify changing the ID for new sessions without patching m-s-m. I will investigate. Changing session IDs on login is desirable: consider a user on a public terminal. Attacker loads the login page for the app and steals the cookie. User comes along and logs in again, (re-using the session id). Now the attacker is also logged in using the old cookie.

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on June 14, 2012 11:50:37_

Great you solved it! To prevent session fixation is the job of auth frameworks as spring security provides it and also tomcat container managed security (form based auth) does it by default.

Still, I'd also be interested why this sessionId reuse is done in tomcat. Maybe I'll ask this on the tomcat-dev list.

In any case, can you please share logs again with the activated session fixation in spring security? In the former logs there seemed to be s.th. not optimal with session locking mode 'auto', so I'd like to review again.

**Comment by google-code-exporter** [comment]
_From [one...@energyhub.net](https://code.google.com/u/104435162650559232740/) on June 14, 2012 12:19:48_

I haven't discovered a way to change the sessionId on login apart from
a) Have the 'SessionFixationStrategy' enabled in Spring Security
AND b) Have this patch in m-s-m

However...
- With these two enabled the login is slow, due to 
"WARNING: Reached timeout when trying to aquire lock for session FBF32ED3B90BCDF1D4E5ABB9922C9F64-n1. Will use this session without this lock."

I'm planning to leave the patch applied to my build of m-s-m, and then in my 'admin' app enable the SS session-fixation-prevention. In my lower-security-requirement apps I will disable the session-fixation-prevention to enable faster logins. 

Later versions of tomcat have a session fixation setting, perhaps m-s-m could also take a setting to enable this patch's behaviour.

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on June 14, 2012 12:53:12_

If you're using tomcat6 you can set emptySessionPath property on the connector to false to prevent sessionId reuse: <a href="http://tomcat.apache.org/tomcat-6.0-doc/config/http.html" rel="nofollow">http://tomcat.apache.org/tomcat-6.0-doc/config/http.html</a>&#13;
&#13;
&gt; - With these two enabled the login is slow, due to &#13;
&gt; "WARNING: Reached timeout when trying to aquire lock for session FBF32ED3B90BCDF1D4E5ABB9922C9F64-n1. Will use this session without this lock."&#13;
&#13;
What do you mean with "With these two enabled"?&#13;
Can you pleaes share logs with your desired scenario, I'd like to see what might be the reason for this.&#13;
&#13;
&gt; Later versions of tomcat have a session fixation setting&#13;
&#13;
This hold only true for tomcat authenticators, for anything else (see e.g. <a href="http://www.tomcatexpert.com/blog/2011/04/25/session-fixation-protection" rel="nofollow">http://www.tomcatexpert.com/blog/2011/04/25/session-fixation-protection</a>). Or is there anything I missed?&#13;
&#13;
Btw, here's my request on the tomcat-dev list: <a href="http://tomcat.10.n6.nabble.com/Why-does-Manager-createSession-String-take-a-sessionId-td4982635.html" rel="nofollow">http://tomcat.10.n6.nabble.com/Why-does-Manager-createSession-String-take-a-sessionId-td4982635.html</a>

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on June 14, 2012 13:21:51_

I already saw in your previously shared logs (<a href="https://gist.github.com/2931870" rel="nofollow">https://gist.github.com/2931870</a>) that on session invalidation the session lock was not freed.&#13;
I submitted this as <a title="When a non-sticky, locked session is expire()'ed the lock should be released" class="closed_ref" href="/p/memcached-session-manager/issues/detail?id=144"> issue #144 </a> and just fixed it.&#13;
&#13;
Though, this shouldn't be the explanation for the lock-acquiry-timeout-warning with session-fixation-protection as in this case the sessionId should be changed and the still existing lock doesn't cause any harm.&#13;
&#13;
So it would be good if you could share logs again so that I can have a look.

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on June 14, 2012 13:27:16_

Anyway, please can you checkout the attached jars with the fix for #144?

**Attachment:** [memcached-session-manager-1.6.2-SNAPSHOT.jar memcached-session-manager-tc6-1.6.2-SNAPSHOT.jar](http://code.google.com/p/memcached-session-manager/issues/detail?id=143#hc8)

**Comment by google-code-exporter** [comment]
_From [one...@energyhub.net](https://code.google.com/u/104435162650559232740/) on June 14, 2012 13:33:14_

I will post the logs and test the fix for #144 as soon as I get a chance.

Yes, we are using emptySessionPath cookies, thanks for that tidbit. We did it on purpose because we serve the same app via several different paths and proxy to the real path in Apache. We could probably re-write the cookie in Apache instead but it's a bit messy.

By 'with these two enabled' I mean 1) Spring Security session-fixation-prevention and 2) My patch to ignore the sessionId in m-s-m.

**Comment by google-code-exporter** [comment]
_From [one...@energyhub.net](https://code.google.com/u/104435162650559232740/) on June 27, 2012 14:18:07_

An update:

We have moved away from empty session path cookies* and the original issue of re-using session IDs is not a problem in that configuration, so we've dropped the patch from above that forces new session ids. This is more a bug in tomcat than m-s-m.

We have also re-enabled Spring Security's session fixation protection which now works just fine.

Thanks again for your help Martin.

* We are re-writing the cookie path in apache using mod_headers (in order to serve one tomcat app on multiple paths via apache reverse proxy).

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on June 28, 2012 01:40:13_

Which version of msm were you using now?

**Comment by google-code-exporter** [comment]
_From [one...@energyhub.net](https://code.google.com/u/104435162650559232740/) on June 28, 2012 04:28:00_

Using master as of yesterday.

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on June 28, 2012 10:05:37_

Ok, good to know the new version is fine. If you want you can send logs so that I can double check that auto locking behaves as it should.
