### ISSUE TITLE
Session timeout event doesn't fired

### ISSUE THREAD

**Issue by ghost** [magro/memcached-session-manager#219]
_From [cj84...@gmail.com](https://code.google.com/u/115897760590879105421/) on September 04, 2013 04:32:10_

<b>What steps will reproduce the problem?</b>
1.Session Timeout Event&#13;
&#13;
<b>What is the expected output? What do you see instead?</b>
Session Timeout Event Fired, Doesn't fired&#13;
&#13;
<b>What version of the product are you using? On what operating system?</b>
memcached-session-manager 1.6.5, tomcat 7.0.42, Cent OS 6.4, Windows 7 64bit, Spring Security Framework + HttpSessionListener&#13;
&#13;
<b>Please provide any additional information below.</b>
if session.invalidate() called, session destroyed event to be fired.&#13;
but... &#13;
When the session expires, the actual session itself has expired and the user can not use.&#13;
but, Session timeout event doesn't fired.&#13;
&#13;
While not using memcached-session-manager, for the same environment, it is handled properly.

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=178_

**Comment by google-code-exporter** [comment]
_From [cj84...@gmail.com](https://code.google.com/u/115897760590879105421/) on September 03, 2013 19:38:41_

+ JDK 1.7 or JDK 1.6

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on September 04, 2013 01:14:00_

Do you use sticky or non-sticky configuration?

**Comment by google-code-exporter** [comment]
_From [cj84...@gmail.com](https://code.google.com/u/115897760590879105421/) on September 04, 2013 01:27:32_

<Manager className="de.javakaffee.web.msm.MemcachedBackupSessionManager"
            memcachedNodes="n1:localhost:11211"
            sticky="false"
            sessionBackupAsync="true"
            memcachedProtocol="binary"
                        operationTimeout="10000"
                        sessionBackupTimeout="10000"
            lockingMode="none"
            requestUriIgnorePattern=".*\.(ico|png|gif|jpg|css|js)$"
            transcoderFactoryClass="de.javakaffee.web.msm.serializer.kryo.KryoTranscoderFactory"
            customConverter="kr.co.infraware.polaris.persistent.kryo.LocaleCustomization"
    />

It's My Configuration.
i used to non-sticky configuration.

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on September 04, 2013 02:56:58_

Ok, then it makes sense. Non-sticky session are removed from the local session map at the end of a request. This is needed to prevent stale session data: assume that tomcat1 serves request1 and sets foo=bar in the session. Afterwards tomcat2 handles request2 and sets foo=baz. Then tomcat1 handles request3, now the session should return foo=baz. If tomcat1 would keep the session locally it would not get the changes done by other instances. Therefore in a non-sticky configuration sessions are only stored in memcached and only loaded to handle a request.

This behaviour should be documented, this is what can be improved. But that it works how it works is "by design" and not a bug - sorry for that ;-)

**Comment by google-code-exporter** [comment]
_From [cj84...@gmail.com](https://code.google.com/u/115897760590879105421/) on September 04, 2013 22:32:10_

yeah. I got it.

I have implemented in a way that avoids this problem.

I solve this problem, but the problem is still present in the environment sticky.


1. Multi-WAS
2. msm is assumed to be a sticky configuration.

L4 or http server environment is set to non-sticky problem arises when the session expires.
(A user -> A WAS request -> C WAS connect -> after session invalid time A WAS Session expired -> A WAS Connect -> A Session Expired)

If you think there is a problem if this portion. document should be updated.

**Comment by google-code-exporter** [comment]
_From [cj84...@gmail.com](https://code.google.com/u/115897760590879105421/) on September 04, 2013 22:33:06_

1. Multi WAS -> Multi WAS, non-sticky loadbalancing

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on September 05, 2013 04:17:47_

A non-sticky loadbalancer in combination with sticky tomcat/msm does not make sense - you'll get stale sessions.
Is the HttpSessionListener also not invoked when you just access one tomcat and wait for session expiration?

**Comment by google-code-exporter** [comment]
_From [cj84...@gmail.com](https://code.google.com/u/115897760590879105421/) on September 05, 2013 22:31:51_

I do not know why it would stale.
anyway, If the answer to the question is ok.

one tomcat, wait for expiration...

then not invoked.

**Comment by google-code-exporter** [comment]
_From [haroldy...@gmail.com](https://code.google.com/u/103627668380965620437/) on April 07, 2015 22:29:44_

Hi cj84..@gmail.com

could you tell me  how u fix this top ?

Thanks.

**Comment by google-code-exporter** [comment]
_From [denis.si...@gmail.com](https://code.google.com/u/105548482992247672762/) on April 09, 2015 10:43:19_

At the moment we reveted the configuration sticky on balancer and sticky on memcached. An initial workaround was the implementation of a thread that destroy the expired sessions.

**Comment by aishydevil12286** [comment]
Hi Martin,

We are observing the same issue in our production system. We are logging the session statistics when the sessionDestroyed method executes for future internal audits. In case of manual logouts it works, but if the session timeouts/expires then the method is not invoked on our HttpSessionListener. Can you please suggest if there is a workaround/fix for this?  

The configuration is as follows:

MSM V1.9.1
JDK 7
Non Sticky
Tomcat 7

**Comment by magro** [comment]
For non sticky sessions the session timeout event cannot be fired because the session does not exist in any tomcat when there's currently no request active for this session. See also my comment above, quoting here:

 Non-sticky session are removed from the local session map at the end of a request. This is needed to prevent stale session data: assume that tomcat1 serves request1 and sets foo=bar in the session. Afterwards tomcat2 handles request2 and sets foo=baz. Then tomcat1 handles request3, now the session should return foo=baz. If tomcat1 would keep the session locally it would not get the changes done by other instances. Therefore in a non-sticky configuration sessions are only stored in memcached and only loaded to handle a request.

**Comment by magro** [comment]
If you're asking for alternative solutions you'd have to describe your specific business requirements/goals.

**Comment by aishydevil12286** [comment]
Thanks for your prompt response Martin. We are actually logging the user session details in a sessionHistory table that maintains session login/logout times for all the system users. This is just for audit purposes. The logout time is updated via the sessionDestroyed method() which worked earlier, but since we switched to MSM, when the user session timeouts, there is no update made with the logout time. So, do you have any suggestions on how to work around this limitation.

**Comment by aishydevil12286** [comment]
If non-sticky sessions are removed from the local session map at the end of a request then by what mechanism are they evicted from memcached nodes? Is it done via MSM or via memcached itself ?

**Comment by aishydevil12286** [comment]
I read your comment at http://grokbase.com/t/gg/memcached-session-manager/1228k1cn41/how-to-trigger-sessiondestroyed-method-when-session-is-timeout 

_"If you really need some HttpSessionListener based functionality a
solution (baked into msm) could be to keep track of session and when
they would expire and just before they expire load them and fire a event
for HttpSessionListers. But this would be rather complex as the question
would be who (which tomcat) should keep track of which session, how to
handle changed session timeouts, moved/relocated session etc. So this
would take some/much time and thoughts to have a stable solution."_

Can you tell how to use this baked in functionality. I think we can use this for our use case.

**Comment by magro** [comment]
There's nothing like that built in, there's even not yet a concept that
could be implemented.

Cheers,
Martin

ash <notifications@github.com> schrieb am Do., 21. Juli 2016, 14:33:

**Comment by aishydevil12286** [comment]
No issues Martin. The whole library is otherwise awesome and I believe we can make other amends in our system to handle this case. 

Thanks!

**Comment by magro** [comment]
Great to hear!

ash <notifications@github.com> schrieb am Do., 21. Juli 2016, 20:27:
