### ISSUE TITLE
When use msm1.9.0 RC1 with KryoTranscoderFactory， throws java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by wenqibo** [magro/memcached-session-manager#275]
<p><a href="https://cloud.githubusercontent.com/assets/4066180/10115816/13f2b63a-644a-11e5-92ef-ab74bccc2ecb.png" target="_blank"><img src="https://cloud.githubusercontent.com/assets/4066180/10115816/13f2b63a-644a-11e5-92ef-ab74bccc2ecb.png" alt="1ce292d3-8a6c-4a5f-9df0-6f1e3e71f1f6" style="max-width:100%;"></a><br>
<a href="https://cloud.githubusercontent.com/assets/4066180/10115817/1422258c-644a-11e5-9359-c58d0bfe263d.png" target="_blank"><img src="https://cloud.githubusercontent.com/assets/4066180/10115817/1422258c-644a-11e5-9359-c58d0bfe263d.png" alt="6d8d6c5e-eed1-40c2-94e8-5ecec36049ae" style="max-width:100%;"></a><br>
<a href="https://cloud.githubusercontent.com/assets/4066180/10115818/14239084-644a-11e5-9d55-0ac98145fe2e.png" target="_blank"><img src="https://cloud.githubusercontent.com/assets/4066180/10115818/14239084-644a-11e5-9d55-0ac98145fe2e.png" alt="53a82c7c-4643-425f-82d3-2412a9dfd1d1" style="max-width:100%;"></a><br>
<a href="https://cloud.githubusercontent.com/assets/4066180/10115860/8c19035c-644b-11e5-84c4-c569731145dc.png" target="_blank"><img src="https://cloud.githubusercontent.com/assets/4066180/10115860/8c19035c-644b-11e5-84c4-c569731145dc.png" alt="e11b2967-6de5-4551-98ba-7b9003711d3a" style="max-width:100%;"></a></p>

![14d4506ea-4eac-4cea-a1dc-1883f969363a](https://cloud.githubusercontent.com/assets/4066180/10116169/e9b37334-645b-11e5-88dd-2c6ab67ff076.png)

**Comment by wenqibo** [comment]
I deploy application as wiki requested：
wiki link：https://code.google.com/p/memcached-session-manager/wiki/SetupAndConfiguration

1.Add memcached-session-manager jars to tomcat
2.Add custom serializers to your webapp

**Comment by magro** [comment]
@wenqibo Looking closer at your screenshot the problem is probably caused by the 2 different asm libs on your webapp classpath: asm-3.3.1 and asm-5.0.3, where 5.0.3 is pulled in by kryo / reflectasm. You might try to exclude 3.3.1 from your dependencies (use `mvn dependency:tree` to see where it gets pulled in), perhaps things are also working with asm 5. Alternatively exclude `com.esotericsoftware:kryo` from msm-kryo-serializers and add a dependency on `com.esotericsoftware:kryo-shaded:3.0.3` - then kryo/reflectasm uses its own relocated version of asm.

If more users run into this issue probably msm-kryo-serializer already should depend on kryo-shaded...

**Comment by wenqibo** [comment]
so..... finally I know . 
Martin,Thank you very much,you are nice man.

**Comment by magro** [comment]
@wenqibo great that it's working now!
