### ISSUE TITLE
Configuring msm with Redis + sticky sessions + kryo

### ISSUE THREAD

**Issue by kisienya** [magro/memcached-session-manager#316]
Hello
Many thanks for this tool,

From your wiki page https://github.com/magro/memcached-session-manager/wiki/SetupAndConfiguration, I have been trying to figure out how to configure Redis msm, but some things escape me especially when configuring context.xml e.g. Setting the Manager class.

Do you have a sample context.xml for  Redis sticky sessions + kryo

Cheers

**Comment by magro** [comment]
Please check out the docs on memcachedNodes in the setup page you mentioned. The failoverNodes property is not needed AFAIK. The rest should be the same as for the regular memcached config. 

@msellinger Are there special things to consider regarding the redis setup? Can you perhaps add a sample context.xml snippet to the setup page, with some hints regarding the assumed redis setup?

**Comment by msellinger** [comment]
As described in the mentioned Wiki page it should be enough to just use a redis:// URL in the memcachedNodes configuration. For example, if Redis is installed on the same server, setting memcachedNodes to "redis://localhost" is enough to serialize the sessions to Redis.

If you want automatic failover, unlike memcached, Redis itself has built-in support for different automatic failover scenarios, e.g. I found the page at http://engineering.bloomreach.com/the-evolution-of-fault-tolerant-redis-cluster/ helpful. Also, if you are using Amazon ElastiCache for Redis, it supports a master-slave configuration with automatic failover out of the box without any special settings in memcached-session-manager.

As for the failoverNodes property, I am not sure how the current implementation handles that with Redis. @magro In my original pull request, I only added support for one single Redis instance in memcachedNodes and no support for failoverNodes (because failover can/should be handled by Redis itself), but we talked about potentially adding support for more advances Redis configurations (e.g. multiple instances), is this something which you introduced when you integrated my pull request?

**Comment by magro** [comment]
@msellinger thanks for commenting! I didn't introduce anything like that. It would probably be good to have a sample snippet with a comment like yours in the setup docs. Can you add this?

**Comment by msellinger** [comment]
Done now!

**Comment by magro** [comment]
Awesome, thanks! 

@kisienya is this helpful, can we close this issue?

**Comment by kisienya** [comment]
Yes this has been very helpfull. You can close. Thanks
